// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Config struct {
	Key       string       `json:"key"`
	Value     string       `json:"value"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type ExtractionJob struct {
	ID              int64          `json:"id"`
	BookTitle       string         `json:"book_title"`
	FilePath        string         `json:"file_path"`
	TotalChunks     sql.NullInt64  `json:"total_chunks"`
	ProcessedChunks sql.NullInt64  `json:"processed_chunks"`
	QuotesExtracted sql.NullInt64  `json:"quotes_extracted"`
	Status          sql.NullString `json:"status"`
	ErrorMessage    sql.NullString `json:"error_message"`
	StartedAt       sql.NullTime   `json:"started_at"`
	CompletedAt     sql.NullTime   `json:"completed_at"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

type Post struct {
	ID                 int64          `json:"id"`
	QuoteID            int64          `json:"quote_id"`
	Platform           string         `json:"platform"`
	PlatformPostID     sql.NullString `json:"platform_post_id"`
	PostUrl            sql.NullString `json:"post_url"`
	TrendID            sql.NullInt64  `json:"trend_id"`
	TrendTitle         string         `json:"trend_title"`
	TrendSource        string         `json:"trend_source"`
	TrendHash          string         `json:"trend_hash"`
	RelevanceScore     float64        `json:"relevance_score"`
	RelevanceReasoning sql.NullString `json:"relevance_reasoning"`
	VectorSimilarity   float64        `json:"vector_similarity"`
	Likes              sql.NullInt64  `json:"likes"`
	Reposts            sql.NullInt64  `json:"reposts"`
	Replies            sql.NullInt64  `json:"replies"`
	PostedAt           sql.NullTime   `json:"posted_at"`
}

type Quote struct {
	ID              int64          `json:"id"`
	Text            string         `json:"text"`
	TextHash        string         `json:"text_hash"`
	SourceBook      string         `json:"source_book"`
	Chapter         sql.NullString `json:"chapter"`
	Character       sql.NullString `json:"character"`
	Themes          string         `json:"themes"`
	ModernRelevance sql.NullString `json:"modern_relevance"`
	Embedding       []byte         `json:"embedding"`
	CharCount       int64          `json:"char_count"`
	TimesPosted     sql.NullInt64  `json:"times_posted"`
	LastPostedAt    sql.NullTime   `json:"last_posted_at"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

type Trend struct {
	ID          int64          `json:"id"`
	Source      string         `json:"source"`
	ExternalID  sql.NullString `json:"external_id"`
	Title       string         `json:"title"`
	Url         sql.NullString `json:"url"`
	Description sql.NullString `json:"description"`
	Score       sql.NullInt64  `json:"score"`
	Embedding   []byte         `json:"embedding"`
	Matched     sql.NullBool   `json:"matched"`
	Skipped     sql.NullBool   `json:"skipped"`
	SkipReason  sql.NullString `json:"skip_reason"`
	DetectedAt  sql.NullTime   `json:"detected_at"`
}
